### ISSUE TITLE
Offset seems to be affected by iOS vh scroll bug

### ISSUE THREAD

**Issue by NCKLS** [kindoflew/svelte-parallax#17]
I'm noticing chopinnes on mobile that seems to be a result of the variable view height on mobile that varies as the address bar expands and detracts.

Here's some more information: https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser

**Comment by NCKLS** [comment]
It seems this is because the height is tied to innerHeight rather than outterHeight.
Are there any plans to make this configurable so the user can decide for their application?

**Comment by kindoflew** [comment]
interesting! thanks for bringing this to my attention! (since `svelte-parallax` just uses `svelte:window`'s `innerHeight` binding, I was hoping there was some sort of behind-the-scenes magic to account for stuff like this, but ¯\\\_(ツ)_/¯)

that's a great idea! i kind of figured someone would eventually want the height of a `section` to be something other than `innerHeight`, so i'm into implementing this.

it should probably (hopefully?) be as simple as adding a `sectionHeight: number` prop to `Parallax` with the default staying `innerHeight`. although, this would mean the user would be responsible for additional `resize` listeners (right now, there is an `on:resize` listener on `svelte:window` to handle that).

**Comment by NCKLS** [comment]
I like the sound of that, seems like a really clean way to go about this and would allow me to use this (super awesome) project for my mobile site as well!

**Comment by kindoflew** [comment]
hey @NCKLS! this feature is now available in `v0.4.0`. Let me know if anything isn't working. Thanks again!
