### ISSUE TITLE
Doesn't seem to work inside a div with overflow: scroll?

### ISSUE THREAD

**Issue by rchrdnsh** [kindoflew/svelte-parallax#7]
Heyo!

Lib looks cool, although it doesn't seem to work inside a fixed position div with overflow: scroll...is that true?

I'm probably doing something wrong, though :-)

**Comment by kindoflew** [comment]
Thanks! I'm pretty sure it won't work inside a scrollable div, because it uses Svelte's `scrollY` binding, which references `window.scrollY`. So the Parallax container wouldn't react to any scroll events in the div because `scrollY` never changes.

Although, exposing which `scrollY` you want as a prop could be a cool idea, I might mess around with that sometime soon.

**Comment by kindoflew** [comment]
I've thought about it more and I'm not going to change anything for now, so I'm going to close this. I'm thinking about (maybe, at some point) refactoring the guts of `Parallax` to use an actual intersection observer, which would probably enable the component to work anywhere, but until then I've just put a note in the `README`. Thanks for pointing this out!

**Comment by rchrdnsh** [comment]
no worries 😁
